#!/usr/bin/env python3
"""
test_aluminum_compatibility.py
Compares GENERATED vs REFERENCE aluminum .mcgpu files column by column,
then plots the MFPs and relative differences.
The material files can be generated by compiling the fortran code and 
redirecting the text file Al_120keV_input.txt to stdin.

Author: Andreu B.; AI assistant: Claude Code Sonnet 4.6 [June 9, 2026]

Run from any directory:
    python3 material_validation/test_aluminum_compatibility.py

Expected files (in the same folder as this script):
    Al_120keV_REFERENCE.mcgpu   Al_120keV_GENERATED.mcgpu
    Al_10MeV_REFERENCE.mcgpu    Al_10MeV_GENERATED.mcgpu
"""

import os
import sys
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

HERE = os.path.dirname(os.path.abspath(__file__))

CASES = [
    {
        'label'  : 'Al 5-120 keV (diagnostic, 23002 bins)',
        'ref'    : os.path.join(HERE, 'Al_120keV_REFERENCE.mcgpu'),
        'gen'    : os.path.join(HERE, 'Al_120keV_GENERATED.mcgpu'),
        'rayleigh_known_diff': True,
    },
    {
        'label'  : 'Al 100 keV-10 MeV (treatment, 100 bins)',
        'ref'    : os.path.join(HERE, 'Al_10MeV_REFERENCE.mcgpu'),
        'gen'    : os.path.join(HERE, 'Al_10MeV_GENERATED.mcgpu'),
        'rayleigh_known_diff': False,
    },
]

# Pass/fail thresholds (relative difference)
THRESH       = 5e-4   # 0.05% for all columns
THRESH_RAY   = 2e-3   # 0.20% for Rayleigh MFP (known direct-vs-spline difference)

MFP_NAMES = ['Energy(eV)', 'Rayleigh MFP', 'Compton MFP', 'Photoelec MFP',
             'Total MFP', 'Rayleigh Pmax']
COLORS    = ['#1f77b4', '#ff7f0e', '#2ca02c', '#111111']   # Ray, Comp, Photo, Total


# ── Parser ────────────────────────────────────────────────────────────────────

def parse_mcgpu(path):
    """Return (mfp_array, rita_rows, shell_rows) from a .mcgpu file."""
    mfp, rita, shells = [], [], []
    section  = 'header'
    next_val = None

    with open(path) as f:
        for line in f:
            s = line.strip()
            if not s:
                continue
            if '[MEAN FREE PATHS' in s and 'Energy' not in s:
                section = 'mfp';     continue
            if '[RAYLEIGH'  in s:    section = 'rita';   continue
            if '[COMPTON'   in s:    section = 'compton'; continue
            if s.startswith('#'):    continue

            fs = s.split()
            if section == 'mfp' and len(fs) >= 5:
                mfp.append([float(x) for x in fs[:6]])
            elif section == 'rita' and len(fs) >= 6:
                rita.append([float(fs[0]), float(fs[1]),
                             float(fs[2]), float(fs[3]),
                             int(fs[4]),   int(fs[5])])
            elif section == 'compton' and len(fs) >= 5:
                shells.append([float(fs[0]), float(fs[1]), float(fs[2]),
                               int(fs[3]),   int(fs[4])])

    return np.array(mfp), rita, shells


# ── Comparison ────────────────────────────────────────────────────────────────

def rel_diff(a, b):
    return np.abs(a - b) / np.maximum(np.maximum(np.abs(a), np.abs(b)), 1e-300)


def compare_case(case):
    """Parse, compare, print results. Return (passed, ref_mfp, gen_mfp)."""
    label = case['label']
    print('\n' + '=' * 65)
    print(label)
    print('=' * 65)

    for key in ('ref', 'gen'):
        if not os.path.exists(case[key]):
            sys.exit(f"ERROR: file not found: {case[key]}")

    ref_mfp, ref_rita, ref_shells = parse_mcgpu(case['ref'])
    gen_mfp, gen_rita, gen_shells = parse_mcgpu(case['gen'])

    all_ok = True

    # MFP table
    print(f"\nMFP table:  ref={len(ref_mfp)} rows   gen={len(gen_mfp)} rows")
    if len(ref_mfp) != len(gen_mfp):
        print("  FAIL: row count mismatch")
        all_ok = False
    n = min(len(ref_mfp), len(gen_mfp))
    for ci, name in enumerate(MFP_NAMES):
        rd  = rel_diff(ref_mfp[:n, ci], gen_mfp[:n, ci])
        mx  = rd.max()
        thr = THRESH_RAY if (ci == 1 and case['rayleigh_known_diff']) else THRESH
        ok  = mx <= thr
        tag = 'PASS' if ok else 'FAIL'
        note = '  <- known direct-vs-spline difference' if (ci == 1 and case['rayleigh_known_diff'] and not ok) else ''
        print(f"  {name:<20}  max={mx:.2e}  [{tag}]{note}")
        all_ok &= ok

    # Rayleigh RITA block (float columns only)
    nray = min(len(ref_rita), len(gen_rita))
    print(f"\nRayleigh RITA:  {nray} rows")
    if len(ref_rita) != len(gen_rita):
        print("  FAIL: row count mismatch");  all_ok = False
    for ci, name in enumerate(['X', 'P', 'A', 'B']):
        ra = np.array([r[ci] for r in ref_rita[:nray]], dtype=float)
        ga = np.array([r[ci] for r in gen_rita[:nray]], dtype=float)
        mx = rel_diff(ra, ga).max()
        ok = mx <= THRESH
        print(f"  {name:<20}  max={mx:.2e}  [{'PASS' if ok else 'FAIL'}]")
        all_ok &= ok
    # Integer columns ITL, ITU
    for ci, name in ((4, 'ITL'), (5, 'ITU')):
        ri = [r[ci] for r in ref_rita[:nray]]
        gi = [r[ci] for r in gen_rita[:nray]]
        ok = (ri == gi)
        print(f"  {name:<20}  exact match  [{'PASS' if ok else 'FAIL'}]")
        all_ok &= ok

    # Compton shells
    ns = min(len(ref_shells), len(gen_shells))
    print(f"\nCompton shells:  {ns}")
    if len(ref_shells) != len(gen_shells):
        print("  FAIL: shell count mismatch");  all_ok = False
    for ci, name in enumerate(['FCO', 'UICO', 'FJ0']):
        ra = np.array([r[ci] for r in ref_shells], dtype=float)
        ga = np.array([r[ci] for r in gen_shells], dtype=float)
        mx = rel_diff(ra, ga).max()
        ok = mx <= THRESH
        print(f"  {name:<20}  max={mx:.2e}  [{'PASS' if ok else 'FAIL'}]")
        all_ok &= ok
    for ci, name in ((3, 'KZCO'), (4, 'KSCO')):
        ri = [r[ci] for r in ref_shells]
        gi = [r[ci] for r in gen_shells]
        ok = (ri == gi)
        print(f"  {name:<20}  exact match  [{'PASS' if ok else 'FAIL'}]")
        all_ok &= ok

    return all_ok, ref_mfp, gen_mfp


# ── Plot ──────────────────────────────────────────────────────────────────────

def make_plots(results):
    """2x2 figure: top=MFP, bottom=relative difference; left=120keV, right=10MeV."""
    fig, axes = plt.subplots(2, 2, figsize=(13, 8))
    fig.suptitle('Aluminum -- MCGPU_material_generator compatibility validation\n'
                 'Reference: PENELOPE 2006 two-step workflow  |  '
                 'Generated: new single-step tool',
                 fontsize=10)

    interaction = ['Rayleigh', 'Compton', 'Photoelectric', 'Total']

    for col, (case, ref_mfp, gen_mfp) in enumerate(results):
        E_keV = ref_mfp[:, 0] / 1e3
        n     = len(E_keV)
        step  = max(1, n // 80)    # subsample markers so they don't hide lines

        ax_mfp  = axes[0, col]
        ax_diff = axes[1, col]

        # -- MFP panel: reference=solid lines, generated=open circle markers
        for i, (name, color) in enumerate(zip(interaction, COLORS)):
            ci = i + 1   # column index in mfp array (skip energy column)
            ax_mfp.semilogy(E_keV, ref_mfp[:, ci],
                            color=color, lw=1.8, ls='-', label=name)
            ax_mfp.semilogy(E_keV[::step], gen_mfp[::step, ci],
                            color=color, ls='none', marker='o', ms=5,
                            markerfacecolor='none', markeredgewidth=1.2)

        # Dummy entries for line-style legend
        ax_mfp.plot([], [], 'k-',  lw=1.8, label='Reference (solid)')
        ax_mfp.plot([], [], 'ko',  ms=5, markerfacecolor='none',
                    markeredgewidth=1.2, label='Generated (circles)')

        ax_mfp.set_title(case['label'], fontsize=9)
        ax_mfp.set_xlabel('Energy (keV)', fontsize=9)
        ax_mfp.set_ylabel('Mean free path (cm)', fontsize=9)
        ax_mfp.set_xlim(E_keV[0], E_keV[-1])
        ax_mfp.legend(fontsize=7, ncol=2)
        ax_mfp.grid(True, which='both', alpha=0.25, lw=0.5)
        ax_mfp.tick_params(labelsize=8)

        # -- Relative difference panel
        floor = 1e-8
        for i, (name, color) in enumerate(zip(interaction, COLORS)):
            ci  = i + 1
            rd  = rel_diff(ref_mfp[:, ci], gen_mfp[:, ci]) * 100   # percent
            ax_diff.semilogy(E_keV, np.maximum(rd, floor),
                             color=color, lw=1.5, label=name)

        # Threshold lines
        ax_diff.axhline(THRESH * 100, color='gray', lw=1.0, ls='--',
                        label=f'Threshold ({THRESH*100:.2f}%)')
        if case['rayleigh_known_diff']:
            ax_diff.axhline(THRESH_RAY * 100, color='salmon', lw=1.0, ls=':',
                            label=f'Rayleigh threshold ({THRESH_RAY*100:.2f}%)')

        ax_diff.set_title('Relative difference -- ' + case['label'].split('(')[0].strip(),
                          fontsize=9)
        ax_diff.set_xlabel('Energy (keV)', fontsize=9)
        ax_diff.set_ylabel('Relative difference (%)', fontsize=9)
        ax_diff.set_xlim(E_keV[0], E_keV[-1])
        ax_diff.set_ylim(floor * 0.5, 1.0)
        ax_diff.legend(fontsize=7, ncol=2)
        ax_diff.grid(True, which='both', alpha=0.25, lw=0.5)
        ax_diff.tick_params(labelsize=8)
        ax_diff.yaxis.set_major_formatter(
            ticker.FuncFormatter(lambda v, _: f'{v:.1g}%'))

    plt.tight_layout(rect=[0, 0, 1, 0.94])
    out = os.path.join(HERE, 'aluminum_validation_plots.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    print(f"\nPlot saved: {out}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("Aluminum compatibility test -- MCGPU_material_generator")

    results = []
    all_ok  = True
    for case in CASES:
        ok, ref_mfp, gen_mfp = compare_case(case)
        results.append((case, ref_mfp, gen_mfp, ok))
        all_ok &= ok

    print('\n' + '=' * 65)
    print('SUMMARY')
    print('=' * 65)
    for case, _, __, ok in results:
        print(f"  [{'PASS' if ok else 'FAIL'}]  {case['label']}")

    print()
    if all_ok:
        print("OVERALL: PASS")
    else:
        print("OVERALL: FAIL -- see details above.")

    make_plots([(c, r, g) for c, r, g, _ in results])

    if not all_ok:
        sys.exit(1)


if __name__ == '__main__':
    main()
